# Generated by Django 6.0 on 2025-12-12 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lots", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lot",
            name="image",
        ),
        migrations.AddField(
            model_name="lot",
            name="main_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="lots/images/",
                verbose_name="Основное изображение",
            ),
        ),
        migrations.CreateModel(
            name="LotImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="lots/gallery/")),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="lots.lot",
                    ),
                ),
            ],
        ),
    ]
