# Generated by Django 6.0 on 2026-02-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lots", "0002_remove_lot_image_lot_main_image_lotimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="lot",
            name="price",
            field=models.IntegerField(
                default=0, help_text="Укажите цену", verbose_name="Цена"
            ),
            preserve_default=False,
        ),
    ]
