# Generated by Django 6.0 on 2026-02-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lots", "0003_lot_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="lot",
            name="preview_image",
            field=models.ImageField(
                blank=True,
                editable=False,
                null=True,
                upload_to="lots/previews/",
                verbose_name="Превью для списка",
            ),
        ),
        migrations.AlterField(
            model_name="lotimage",
            name="image",
            field=models.ImageField(
                upload_to="lots/gallery/", verbose_name="Доп. фото"
            ),
        ),
    ]
