# Generated by Django 6.0 on 2026-02-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lots", "0004_lot_preview_image_alter_lotimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="lotimage",
            name="preview_image",
            field=models.ImageField(
                blank=True,
                editable=False,
                null=True,
                upload_to="lots/gallery_previews/",
                verbose_name="Доп. фото (превью)",
            ),
        ),
    ]
