# Generated by Django 6.0 on 2026-02-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramdialog",
            name="status",
            field=models.CharField(
                choices=[("open", "Открыт"), ("closed", "Закрыт")],
                default="open",
                max_length=20,
            ),
        ),
    ]
