# Generated by Django 6.0 on 2026-02-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0002_telegramdialog_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramdialog",
            name="topic_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
