# Generated by Django 6.0 on 2026-02-07 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0003_telegramdialog_topic_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramdialog",
            name="last_admin_msg_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
