# Generated by Django 6.0 on 2026-02-07 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("telegram_bot", "0004_telegramdialog_last_admin_msg_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="telegramdialog",
            name="last_admin_msg_id",
        ),
    ]
